import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/ProductPage.module.css'
import React from 'react'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import FooterBanner from '../../components/FooterBanner'
import HeroBanner from '../../components/HeroBanner'
import Cart from '../../components/Cart'
import Layout from '../../components/Layout'
import Rating from '@mui/material/Rating';
import ProductItem from '../../components/Product'
import { axiosReq } from '../../util/apiCalls'
import { useEffect, useState } from 'react'

import {useStateContext} from '../../context/StateContext'

export default function Product() {
  const [showCart, setShowCart] = useState(false)

    const [value, setValue] = React.useState(2);
    //const [quantity, setQuantity] = React.useState(1);
    const [product, setProduct] = React.useState(null);
    const [products, setProducts] = React.useState(null);
    const {decQty, incQty, qty, onAdd, cartItems} = useStateContext()

    useEffect(() => {
      const getProduct = async () => {
        try {
          const id = location.pathname.split('/')[2]
          const res = await axiosReq.get(`product/${id}`, {params: {id: id}})
          setProduct(res.data)
        } catch (error) {
          console.log(error);
        }
      }
      const getproducts = async () => {
        try {
          const products = await axiosReq.get("products/");
          setProducts(products.data)
        } catch (error) {
          console.log(error);
        }
      }
      getproducts()
      getProduct()
  }, [])

  const handleBuy = async () => {
    onAdd(product, qty)
    setShowCart(true)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Phanox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar showCart={showCart} setShowCart={setShowCart}/>
      <div className={showCart ? `${styles.productContainer} ${styles.opacity}` : styles.productContainer}>
        <div className={styles.image}>
            <img src={product?.image} alt="headphones"/>
        </div>
        <div className={styles.info}>
            <h2>{product?.name}</h2>
            <Rating
                name="simple-controlled"
                value={value}
                onChange={(event, newValue) => {
                setValue(newValue);
                }}
            />
            <span className={styles.details}>Details: </span>
            <p>{product?.details}</p>
            <span className={styles.price}>${product?.price}</span>
            <div className={styles.quantity}>
                <span>Quantity:</span>
                <span className={styles.quantityActions}>
                    <span onClick={decQty}>-</span>
                    <span>{qty}</span>
                    <span onClick={incQty}>+</span>
                </span>
            </div>
            <div className={styles.actions}>
                <button className={styles.add} onClick={() => onAdd(product, qty)}>Add to cart</button>
                <button className={styles.buy} onClick={handleBuy}>Buy now</button>
            </div>
        </div>
      </div>
      
      <div className={styles.productsWrapper}>
        <h2>You May also like</h2>
        <div className={styles.marquee}>
            <div className={`${styles.productsContainer} ${styles.track}`}>
              {products?.map((product) => (
              <ProductItem key={product._id} product={product} />
            ))}
            </div>
        </div>
      </div>
      <Footer />
      {showCart && (
        <Cart setShowCart={setShowCart}/>
      )}
    </div>
  )
}

