import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import FooterBanner from '../components/FooterBanner'
import HeroBanner from '../components/HeroBanner'
import Layout from '../components/Layout'
import Product from '../components/Product'
import Cart from '../components/Cart'
import { axiosReq } from '../util/apiCalls'


export default function Home() {
  const [showCart, setShowCart] = useState(false)
  const [products, setProducts] = useState(null)

  useEffect(() => {
    const getproducts = async () => {
      try {
        const products = await axiosReq.get("products/");
        setProducts(products.data)
      } catch (error) {
        console.log(error);
      }
    }
    getproducts()
  }, []);
  console.log(products);
  return (
    <div className={styles.container}>
      <Head>
        <title>Phanox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>
      <Navbar showCart={showCart} setShowCart={setShowCart} />
      <div className={showCart ? `${styles.heroBannerContainer} ${styles.opacity}` : styles.heroBannerContainer}>
        <HeroBanner />
      </div>
      <div className={showCart ? `${styles.productsWrapper} ${styles.opacity}` : styles.productsWrapper}>
        <h2>Best Seller Products</h2>
        <p>speaker There are many variations passages</p>
        <div className={styles.productsContainer}>
          {products?.map((product) => (
            <Product key={product._id} product={product} />
          ))}
        </div>
      </div>
      <div className={styles.heroBannerContainer}>
        <FooterBanner />
      </div>
      <Footer />
      {showCart && (
        <Cart setShowCart={setShowCart}/>
      )}
    </div>
  )
}
